import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#E8E6E1",
  },
  listContent: {
    paddingTop: 80,
    paddingHorizontal: 20,
    paddingBottom: 140,
  },
  emptyContainer: {
    alignItems: "center",
    marginTop: 100,
  },
  emptyText: {
    fontSize: 18,
    color: "#666",
  },
  notificationItem: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: 20,
    paddingHorizontal: 20,
    borderRadius: 16,
    marginBottom: 12,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
  },
  unreadItem: {
    borderWidth: 2,
    borderColor: "#5D4037",
  },
  recipeName: {
    fontSize: 18,
    fontWeight: "500",
    color: "#333",
    flex: 1,
  },
  userImage: {
    width: 50,
    height: 50,
    borderRadius: 25,
  },
  bottomButtons: {
    flexDirection: "row",
    gap: 20,
    position: "absolute",
    bottom: 20,
    left: 0,
    right: 0,
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 20,
  },
  profileButton: {
    width: 100,
    height: 100,
    borderRadius: 50,
    backgroundColor: "rgba(169, 149, 108, 0.75)",
    borderWidth: 3,
    borderColor: "#5D4037",
    overflow: "hidden",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 4,
    elevation: 3,
    alignItems: "center",
    justifyContent: "center",
  },
  profileImage: {
    width: "100%",
    height: "100%",
  },
  placeholderImage: {
    width: "100%",
    height: "100%",
    backgroundColor: "#E8E4FF",
    alignItems: "center",
    justifyContent: "center",
  },
  placeholderText: {
    fontSize: 40,
    fontWeight: "700",
    color: "#9B8FE8",
  },
  modalOverlay: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  modalBackground: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "rgba(0, 0, 0, 0.5)",
  },
  modalContent: {
    width: 320,
    backgroundColor: "#FFFFFF",
    borderRadius: 20,
    padding: 20,
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 8,
  },
  modalButton: {
    width: "100%",
    paddingVertical: 16,
    backgroundColor: "#FFFFFF",
    borderRadius: 12,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: "#DDD",
  },
  modalButtonText: {
    fontSize: 16,
    textAlign: "center",
    color: "#333",
  },
  modalRejectButton: {
    width: "100%",
    paddingVertical: 16,
    backgroundColor: "#FFFFFF",
    borderRadius: 12,
    marginBottom: 20,
    borderWidth: 1,
    borderColor: "#DDD",
  },
  modalRejectText: {
    fontSize: 14,
    textAlign: "center",
    color: "#666",
  },
  modalActions: {
    flexDirection: "row",
    gap: 40,
  },
  rejectIcon: {
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: "#FFCDD2",
    alignItems: "center",
    justifyContent: "center",
  },
  approveIcon: {
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: "#C8E6C9",
    alignItems: "center",
    justifyContent: "center",
  },
  iconText: {
    fontSize: 32,
    fontWeight: "bold",
    color: "#333",
  },
});

export default styles;