import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#E8E6E1",
    paddingTop: 60,
    paddingHorizontal: 20,
    paddingBottom: 40,
  },
  headerText: {
    fontSize: 13,
    color: "#888",
    fontWeight: "400",
    marginBottom: 40,
    textAlign: "center",
  },
  card: {
    flex: 1,
    alignItems: "center",
    paddingTop: 20,
  },
  imageContainer: {
    position: "relative",
    marginBottom: 30,
  },
  profileImage: {
    width: 270,
    height: 270,
    borderRadius: 135,
    borderWidth: 5,
    borderColor: "#5D4037",
  },
  placeholderImage: {
    width: 270,
    height: 270,
    borderRadius: 135,
    borderWidth: 5,
    borderColor: "#5D4037",
    backgroundColor: "#E8E4FF",
    alignItems: "center",
    justifyContent: "center",
  },
  placeholderText: {
    fontSize: 100,
    fontWeight: "700",
    color: "#9B8FE8",
  },
  uploadingOverlay: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    borderRadius: 135,
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    alignItems: "center",
    justifyContent: "center",
  },
  editIcon: {
  position: "absolute",
  right: 10,
  bottom: 10,
  width: 80,
  height: 80,
  borderRadius: 40,
  backgroundColor: "#5D4037",
  alignItems: "center",
  justifyContent: "center",
  shadowColor: "#000",
  shadowOffset: { width: 0, height: 2 },
  shadowOpacity: 0.2,
  shadowRadius: 3,
  elevation: 3,
}, 
  colorPreview: {
  width: 70,
  height: 70,
  borderRadius: 40,
},
  usernameInput: {
  width: 262,
  height: 65,
  backgroundColor: "#FFFFFF",
  borderWidth: 0,
  borderRadius: 10,
  paddingHorizontal: 20,
  fontSize: 40,  
  fontWeight: "400", 
  textAlign: "center",
  marginBottom: 20,
  shadowColor: "#000",
  shadowOffset: { width: 0, height: 1 },
  shadowOpacity: 0.08,
  shadowRadius: 2,
  elevation: 1,
  justifyContent: "center", 
  alignItems: "center",    
},

usernameText: {
  fontSize: 40,
  fontWeight: "400",
  color: "#333",
},
  button: {
    width: 262,
    height: 65,
    backgroundColor: "#FFFFFF",
    borderWidth: 0,
    borderRadius: 10,
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 16,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.08,
    shadowRadius: 2,
    elevation: 1,
  },
  buttonText: {
    fontSize: 40,
    color: "#333",
    fontWeight: "400",
  },
  bottomContainer: {
    position: "absolute",
    bottom: 10,
    left: 0,
    right: 0,
    flexDirection: "row",
    alignItems: "center",
  },
  leftSide: {
    flex: 1,
    alignItems: "flex-start",
    paddingLeft: 10,
  },
  centerSide: {
    flex: 1,
    alignItems: "center",
  },
  rightSide: {
    flex: 1,
    alignItems: "flex-end",
    paddingRight: 10,
  },
  iconButton: {
    width: 100,
    height: 100,
    borderRadius: 50,
    backgroundColor: "rgba(169, 149, 108, 0.75)",
    borderWidth: 3,
    borderColor: "#5D4037",
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 4,
    elevation: 3,
  },
  iconButtonText: {
    fontSize: 36,
  },
  icon: {
    width: 50,
    height: 50,
    resizeMode: "contain",
  },
});

export default styles;