import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#E8E6E1",
  },
  scrollContent: {
    paddingTop: 60,
    paddingHorizontal: 20,
    paddingBottom: 140,
    alignItems: "center",
  },
  imageContainer: {
    position: "relative",
    marginBottom: 30,
  },
  kitchenImage: {
    width: 270,
    height: 270,
    borderRadius: 135,
    borderWidth: 5,
    borderColor: "#5D4037",
  },
  placeholderImage: {
    width: 270,
    height: 270,
    borderRadius: 135,
    borderWidth: 5,
    borderColor: "#5D4037",
    backgroundColor: "#E8E4FF",
    alignItems: "center",
    justifyContent: "center",
  },
  placeholderText: {
    fontSize: 100,
    fontWeight: "700",
    color: "#5D4037",
  },
  uploadingOverlay: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    borderRadius: 135,
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    alignItems: "center",
    justifyContent: "center",
  },
  colorButton: {
    position: "absolute",
    right: 10,
    bottom: 10,
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: "#5D4037",
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 3,
    elevation: 3,
  },
  colorPreview: {
    width: 70,
    height: 70,
    borderRadius: 35,
  },
  button: {
    width: 262,
    height: 65,
    backgroundColor: "#FFFFFF",
    borderRadius: 10,
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 16,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.08,
    shadowRadius: 2,
    elevation: 1,
  },
  buttonText: {
    fontSize: 40,
    color: "#333",
    fontWeight: "400",
  },
  membersContainer: {
    width: "100%",
    marginTop: 20,
  },
  memberRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    width: 262,
    height: 65,
    backgroundColor: "#FFFFFF",
    borderRadius: 10,
    paddingHorizontal: 20,
    marginBottom: 12,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.08,
    shadowRadius: 2,
    elevation: 1,
  },
  memberName: {
    fontSize: 32,
    color: "#333",
    fontWeight: "400",
  },
  removeButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "#FFCDD2",
    alignItems: "center",
    justifyContent: "center",
  },
  removeButtonText: {
    fontSize: 24,
    color: "#C62828",
    fontWeight: "bold",
  },
  bottomContainer: {
    position: "absolute",
    bottom: 10,
    left: 0,
    right: 0,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 10,
  },
  leftSide: {
    flex: 1,
    alignItems: "flex-start",
  },
  rightSide: {
    flex: 1,
    alignItems: "flex-end",
  },
});

export default styles;