import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#E8E6E1",
    paddingBottom: 40, 
  },
  scrollContent: {
    paddingTop: 60,
    paddingHorizontal: 20,
    paddingBottom: 140,
  },
  profileSection: {
    alignItems: "center",
    marginBottom: 40,
  },
  profileButton: {
    width: 120,
    height: 120,
    borderRadius: 60,
    overflow: "hidden",
  },
  profileImage: {
    width: "100%",
    height: "100%",
  },
  placeholderImage: {
    width: "100%",
    height: "100%",
    backgroundColor: "#E8E4FF",
    alignItems: "center",
    justifyContent: "center",
  },
  placeholderText: {
    fontSize: 48,
    fontWeight: "700",
    color: "#9B8FE8",
  },
  kitchensList: {
    gap: 16,
  },
  kitchenButton: {
  flex: 1,
  flexDirection: "row",
  alignItems: "center",
  justifyContent: "space-between",
  paddingVertical: 20,
  paddingHorizontal: 54,
  borderRadius: 16,
  backgroundColor: "#FFFFFF",
  shadowColor: "#000",
  shadowOffset: { width: 0, height: 2 },
  shadowOpacity: 0.1,
  shadowRadius: 4,
  elevation: 2,
  position: "relative",
},
colorCircle: {
  position: "absolute",
  right: 12,
  width: 50,
  height: 50,
  borderRadius: 25,
  alignItems: "center",
  justifyContent: "center",
},
  kitchenIcon: {
    fontSize: 32,
    marginRight: 16,
    color: "#5D4037",
  },
  kitchenName: {
  fontSize: 24,
  fontWeight: "500",
  color: "#333",
  flex: 1,
  textAlign: "center",
  marginRight: 50,
},
  bottomContainer: {
    position: "absolute",
    bottom: 10,
    left: 0,
    right: 0,
    flexDirection: "row",
    alignItems: "center",
  },
  leftSide: {
    flex: 1,
    alignItems: "flex-start",
    paddingLeft: 10,
  },
  centerSide: {
    flex: 1,
    alignItems: "center",
  },
  rightSide: {
    flex: 1,
    alignItems: "flex-end",
    paddingRight: 10,
  },
  addButton: {
    width: 100,
    height: 100,
    borderRadius: 50,
    backgroundColor: "rgba(169, 149, 108, 0.75)",
    borderWidth: 3,
    borderColor: "#5D4037",
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 4,
    elevation: 3,
  },
  addButtonText: {
    fontSize: 48,
    color: "#5D4037",
    fontWeight: "300",
  },
  profileButtonBottom: {
    width: 100,
    height: 100,
    borderRadius: 50,
    backgroundColor: "rgba(169, 149, 108, 0.75)",
    borderWidth: 3,
    borderColor: "#5D4037",
    overflow: "hidden",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 4,
    elevation: 3,
    alignItems: "center",
    justifyContent: "center",
  },
  profileImageSmall: {
    width: "100%",
    height: "100%",
  },
  placeholderImageSmall: {
    width: "100%",
    height: "100%",
    backgroundColor: "#E8E4FF",
    alignItems: "center",
    justifyContent: "center",
  },
  placeholderTextSmall: {
    fontSize: 40,
    fontWeight: "700",
    color: "#9B8FE8",
  },
    kitchenRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  colorEditButton: {
  width: "100%",
  height: "100%",
  alignItems: "center",
  justifyContent: "center",
},
  colorEditIcon: {
    fontSize: 20,
    color: "#5D4037",
  },
});

export default styles;